export const SUCCESS_LOG_IN_RESPONSE = 'SUCCESS_LOG_IN_RESPONSE';
export const ERROR_LOG_IN_RESPONSE = 'ERROR_LOG_IN_RESPONSE';
export const LOG_OUT = 'LOG_OUT';
export const STUDENT_SIGN_UP = 'STUDENT_SIGN_UP';
export const COMPANY_SIGN_UP = 'COMPANY_SIGN_UP';

export const STUDENT_PROFILES_LOADING = 'STUDENT_PROFILES_LOADING';
export const STUDENT_PROFILES_DATA = 'STUDENT_PROFILES_DATA';
export const STUDENT_PROFILES_ERROR = 'STUDENT_PROFILES_ERROR';

export const EVENT_DETAILS_DATA = 'EVENT_DETAILS_DATA'
export const EVENT_DETAILS_ERROR = 'EVENT_DETAILS_ERROR'
export const EVENT_SEARCH_DETAILS_ERROR = 'EVENT_SEARCH_DETAILS_ERROR';
export const EVENT_SEARCH_DETAILS_DATA = 'EVENT_SEARCH_DETAILS_DATA';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';
export const EVENT_REGISTERED_STUDENTS = 'EVENT_REGISTERED_STUDENTS'; 

export const COMPANY_PROFILE_DATA = 'COMPANY_PROFILE_DATA';
export const COMPANY_PROFILE_ERROR = 'COMPANY_PROFILE_ERROR';
export const UPDATE_COMPANY_PROFILE_SUCCESS = 'UPDATE_COMPANY_PROFILE_SUCCESS';
export const UPDATE_COMPANY_PROFILE_ERROR = 'UPDATE_COMPANY_PROFILE_ERROR';

export const ALL_JOB_APPLICATIONS = 'ALL_JOB_APPLICATIONS';
export const COMAPANY_JOB_POSTINGS = 'COMAPANY_JOB_POSTINGS';
export const CHANGE_JOB_APPLICATION_STATUS = 'CHANGE_JOB_APPLICATION_STATUS';
export const JOB_POSTING_CREATE = 'JOB_POSTING_CREATE';

export const STUDENT_JOB_APPLICATIONS = 'STUDENT_JOB_APPLICATIONS';
export const STUDENT_JOBS = 'STUDENT_JOBS';

export const JOB_POSTING_SHOW = 'JOB_POSTING_SHOW';
export const JOB_POSTING_APPLY = 'JOB_POSTING_APPLY';
export const JOB_POSTING_STATUS = 'JOB_POSTING_STATUS';

export const MESSAGE_SHOW = 'MESSAGE_SHOW';
export const MESSAGE_SEND = 'MESSAGE_SEND';

export const STUDENT_PROFILE_SHOW = 'STUDENT_PROFILE_SHOW';
export const STUDENT_PROFILE_EDIT = 'STUDENT_PROFILE_EDIT';
export const STUDENT_PROFILE_PIC_UPDATE = 'STUDENT_PROFILE_PIC_UPDATE';
export const STUDENT_PROFILE_PIC_UPDATE_ERROR = 'STUDENT_PROFILE_PIC_UPDATE_ERROR';
export const EDUCATION_DETAIL_EDIT = 'EDUCATION_DETAIL_EDIT';
export const EDUCATION_DETAIL_CLICK_EDIT = 'EDUCATION_DETAIL_CLICK_EDIT';
export const EDUCATION_DETAIL_DELETE = 'EDUCATION_DETAIL_DELETE';
export const EXPERIENCE_DETAIL_EDIT = 'EXPERIENCE_DETAIL_EDIT';
export const EXPERIENCE_DETAIL_CLICK_EDIT = 'EXPERIENCE_DETAIL_CLICK_EDIT';
export const EXPERIENCE_DETAIL_DELETE = 'EXPERIENCE_DETAIL_DELETE';


